name: C/C++ CI

on: [push]

jobs:fuctioning wallet alert issue
  build:wallet alert

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: make

